kind: pipeline
type: docker
name: awsbuilders-poweron

clone:
  disable: true

steps:
- name: start-aws-instances
  pull: always
  image: amazon/aws-cli
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  commands:
    - aws ec2 start-instances --region eu-north-1 --instance-ids i-01e3d598710a23947

trigger:
  branch:
    include:
    - master
    - main
  event:
    include:
    - push
    - pull_request
    - tag





# Build latest images

---

kind: pipeline
type: docker
name: build-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: build-webkitondocker-amd64
  image: plugins/docker
  pull: always
  settings:
    repo: walkero/webkitondocker
    tags:
      - latest
    cache_from:
      - walkero/webkitondocker:latest
    dockerfile: Dockerfile
    purge: true
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

trigger:
  branch:
    include:
    - master
    - main
  event:
    include:
    - push

depends_on:
  - awsbuilders-poweron

node:
  agents: awsbuilders

# ---

# kind: pipeline
# type: docker
# name: build-arm64

# platform:
#   arch: arm64
#   os: linux

# steps:
# - name: build-webkitondocker-arm64
#   image: plugins/docker
#   pull: always
#   settings:
#     repo: walkero/webkitondocker
#     tags:
#       - latest-arm64
#     cache_from:
#       - walkero/webkitondocker:latest-arm64
#     dockerfile: Dockerfile
#     purge: true
#     username:
#       from_secret: DOCKERHUB_USERNAME
#     password:
#       from_secret: DOCKERHUB_PASSWORD

# trigger:
#   branch:
#     include:
#     - master
#     - main
#   event:
#     include:
#     - push


# ---
# kind: pipeline
# name: manifest-webkitondocker

# steps:
# - name: manifest-webkitondocker-latest
#   image: plugins/manifest
#   settings:
#     username:
#       from_secret: DOCKERHUB_USERNAME
#     password:
#       from_secret: DOCKERHUB_PASSWORD
#     target: walkero/webkitondocker:latest
#     template: walkero/webkitondocker:latest-ARCH
#     platforms:
#       - linux/amd64
#       - linux/arm64

# depends_on:
#   - build-amd64
#   - build-arm64

# trigger:
#   branch:
#     include:
#     - master
#     - main
#   event:
#     include:
#     - push




# # Builg images from TAG

---

kind: pipeline
type: docker
name: build-amd64-from-tag

platform:
  arch: amd64
  os: linux

steps:
- name: build-webkitondocker-tag-amd64
  image: plugins/docker
  pull: always
  settings:
    repo: walkero/webkitondocker
    tags:
      - ${DRONE_TAG/\//-}-amd64
    cache_from:
      - walkero/webkitondocker:latest-amd64
    dockerfile: Dockerfile
    purge: true
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

trigger:
  event:
    include:
    - tag

depends_on:
  - awsbuilders-poweron

node:
  agents: awsbuilders

# ---

# kind: pipeline
# type: docker
# name: build-arm64-from-tag

# platform:
#   arch: arm64
#   os: linux

# steps:
# - name: build-webkitondocker-tag-arm64
#   image: plugins/docker
#   pull: always
#   settings:
#     repo: walkero/webkitondocker
#     tags:
#       - ${DRONE_TAG/\//-}-arm64
#     cache_from:
#       - walkero/webkitondocker:latest-arm64
#     dockerfile: Dockerfile
#     purge: true
#     username:
#       from_secret: DOCKERHUB_USERNAME
#     password:
#       from_secret: DOCKERHUB_PASSWORD

# trigger:
#   event:
#     include:
#     - tag

# depends_on:
#   - awsbuilders-poweron

# node:
#   agents: awsbuilders

# ---
# kind: pipeline
# name: manifest-webkitondocker-from-tag

# steps:
# - name: manifest-webkitondocker-tag
#   image: plugins/manifest
#   settings:
#     username:
#       from_secret: DOCKERHUB_USERNAME
#     password:
#       from_secret: DOCKERHUB_PASSWORD
#     target: walkero/webkitondocker:${DRONE_TAG/\//-}
#     template: walkero/webkitondocker:${DRONE_TAG/\//-}-ARCH
#     platforms:
#       - linux/amd64
#       - linux/arm64

# depends_on:
#   - build-amd64-from-tag
#   - build-arm64-from-tag

# trigger:
#   event:
#     include:
#     - tag